import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { ChevronLeft } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";
import { Providers } from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full !scroll-smooth" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased relative",
          GeistSans.variable,
          GeistMono.variable
        )}
      >
        <Providers>
          <Link
            href="/"
            className={cn(
              buttonVariants({
                variant: "ghost",
              }),
              "absolute left-4 top-4 md:left-8 md:top-8"
            )}
          >
            <ChevronLeft className="size-4 mr-2" />
            Retour
          </Link>
          {children}
        </Providers>
      </body>
    </html>
  );
}
