import { auth } from "@/auth";
import AdminPanelLayout from "@/components/admin-panel/AdminPanelLayout";
import { cn } from "@/lib/utils";
import { TailwindIndicator } from "@/utils/TailwindIndicator";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import "../globals.css";
import { Providers } from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (session?.user.role !== "ADMIN") {
    return redirect("/");
  }
  return (
    <html lang="en" className="h-full !scroll-smooth" suppressHydrationWarning>
      <body
        className={cn(
          "h-full bg-background font-sans antialiased",
          GeistSans.variable,
          GeistMono.variable
        )}
      >
        <Providers>
          <AdminPanelLayout>{children}</AdminPanelLayout>
          <TailwindIndicator />
        </Providers>
      </body>
    </html>
  );
}
